### PR TITLE
Feature/hooks unit test

### PR DESCRIPTION
**Pull request by anton-karlovskiy**

### CODE REVIEW

**Comment by anton-karlovskiy** [comment]
The last commits are mainly for error boundary implementation.
I should have created another branch for it according to gitflow.
I just pushed that implementation as well in this PR, since many conflicts are expected otherwise.

**Comment by addyosmani** [comment]
@housseindjirdeh would love your help with this one if you have time :) - it's the event listener issues around the battery test (for battery-aware resource loading). 

It's probably going to take me a few days to circle back, but it would be great to get our initial unit tests for the project across the finishing line. I'm comfortable with either providing pointers to Anton or making changes directly to the PR if he would prefer that.

After talking it over with @anton-karlovskiy:

>  I think we've found the correct way and written a successful test on the event listener regarding network.test.js. But we have one more, Battery, I've been trying to figure out but not found the cause.

> Those are implemented here. (focusing on battery and network directories)
https://github.com/anton-karlovskiy/react-hooks-unit-test.git

> You can try the Unit Test by running command. "npm install && npm run test". Everything passes except for event listener test in battery. The event listener callback is bound function and not tested as I expected. In the codebase I wrapped the corresponding test part with "ray test touch" and also commented my thought("FYI") on the expected behavior https://github.com/airbnb/enzyme/issues/426#issuecomment-228601631" This is the approach I took.

> The interesting thing is that it's working well in network.test.js: https://www.dropbox.com/s/tijgy2zsy8sbjnx/bound-function.PNG?dl=0

> Like this, with bound functions as event listener callbacks. Please review the comment I left in the battery.test.js.

Feel free to ask follow-up questions as needed on here

**Comment by housseindjirdeh** [comment]
@anton-karlovskiy it does look you're binding the event listener callback just fine 🤔, but I can't help but think it's not being hooked to `result.current` as it should?

Commenting out your two lines of code in the `act` call also still seems to fail the test:

      act(() => {
        const listenerCallback = result.current.updateBatteryStatus.bind(null, updatedBattery);
        listenerCallback(updatedBattery);

        map.levelchange(updatedBattery);
      });

But similarly, just binding the event listener `updateBatteryStatus` directly to `result.current`'s update method works:

````
try {
  const { result, waitForNextUpdate } = renderHook(() => useBatteryStatus());
  await waitForNextUpdate();

  const updatedBattery = {
    chargingTime: 30,
    dischargingTime: 50,
    level: 60,
    charging: false
  };
  
  battery.addEventListener('levelchange', result.current.updateBatteryStatus); // <---

  act(() => {
    map.levelchange(updatedBattery);
  })

  ...
````

@anton-karlovskiy would it be possible to do something similar and just explicitly add the event listener within the try block and not map it at the beginning?

**Comment by anton-karlovskiy** [comment]
> @anton-karlovskiy it does look you're binding the event listener callback just fine 🤔, but I can't help but think it's not being hooked to `result.current` as it should?
> 
> Commenting out your two lines of code in the `act` call also still seems to fail the test:
> 
> ```
>   act(() => {
>     const listenerCallback = result.current.updateBatteryStatus.bind(null, updatedBattery);
>     listenerCallback(updatedBattery);
> 
>     map.levelchange(updatedBattery);
>   });
> ```
> 
> But similarly, just binding the event listener `updateBatteryStatus` directly to `result.current`'s update method works:
> 
> ```
> try {
>   const { result, waitForNextUpdate } = renderHook(() => useBatteryStatus());
>   await waitForNextUpdate();
> 
>   const updatedBattery = {
>     chargingTime: 30,
>     dischargingTime: 50,
>     level: 60,
>     charging: false
>   };
>   
>   battery.addEventListener('levelchange', result.current.updateBatteryStatus); // <---
> 
>   act(() => {
>     map.levelchange(updatedBattery);
>   })
> 
>   ...
> ```
> 
> @anton-karlovskiy would it be possible to do something similar and just explicitly add the event listener within the try block and not map it at the beginning?

Thank you for your care. Let me try.

**Comment by anton-karlovskiy** [comment]
act(() => {
    const listenerCallback = result.current.updateBatteryStatus.bind(null, updatedBattery);
    listenerCallback(updatedBattery);

    map.levelchange(updatedBattery);
  });

**Comment by anton-karlovskiy** [comment]
I've been debugging this issue again. I think the cause of this issue is related to Javascript scope.
So I'd like to accept @housseindjirdeh's suggestion.
Or we can mock the listener testing like the following.
```
act(() => {
    const anonymousListenerCallback = result.current.updateBatteryStatus.bind(null, updatedBattery);
    anonymousListenerCallback(updatedBattery);
});
```

**Comment by housseindjirdeh** [comment]
Thanks for spending the time to really look into this @anton-karlovskiy. It definitely looks like an issue related to scope.

Mocking the listener and directly firing it seems like a viable option. Only thing is from a readability perspective, it might look confusing if `levelchange` isn't called anywhere. But the idea still holds (since my suggestion just connects `updateBatteryStatus` as the listener which is ultimately doing the same thing :))

**Comment by anton-karlovskiy** [comment]
> Thanks for spending the time to really look into this @anton-karlovskiy. It definitely looks like an issue related to scope.
> 
> Mocking the listener and directly firing it seems like a viable option. Only thing is from a readability perspective, it might look confusing if `levelchange` isn't called anywhere. But the idea still holds (since my suggestion just connects `updateBatteryStatus` as the listener which is ultimately doing the same thing :))

Thank you for your suggestion.
Could you please illustrate some code snippets for my better understanding?

**Comment by housseindjirdeh** [comment]
Was just referring to how the code might look like mocking the listener call directly. For example:

```
const battery = {
  chargingTime: 20,
  dischargingTime: 40,
  level: 50,
  charging: true
};


//...

try {
  const { result, waitForNextUpdate } = renderHook(() => useBatteryStatus());
  await waitForNextUpdate();

  const updatedBattery = {
    ...
  };

  act(() => {
    const anonymousListenerCallback = result.current.updateBatteryStatus.bind(null, updatedBattery);
    anonymousListenerCallback(updatedBattery);
  })

 expect...
```

This passes, but no there's event listener used for `levelchange` similar to how the [API](https://googlechrome.github.io/samples/battery-status/) expects you to set it up. For someone reading this code for the first time, they may wonder why there's no mention of `levelchange` since the unit test is supposed to test that :)

My previous suggestion just added the listener directly:

```
battery.addEventListener('levelchange', result.current.updateBatteryStatus);
```

Which ultimately does the same thing your code is doing (firing updateBatteryStatus) but I think it would be nice to see the event listener set up in the test

I hope that makes sense, let me know if there's anything you're still thinking however!

**Comment by anton-karlovskiy** [comment]
@housseindjirdeh
Yes I've got your points.
One thing I've found that in batter/index.js if we remove the line 29.
```
battery.addEventListener('levelchange', updateBatteryStatus.bind(null, battery));
```
We can pass Unit Test because we manually defined this again in the test.js file, which does not make much sense in my opinion.
```
battery.addEventListener('levelchange', result.current.updateBatteryStatus.bind(null, updatedBattery));
map.levelchange(updatedBattery);
```

**Comment by anton-karlovskiy** [comment]
Hi @housseindjirdeh,

Please have a look at this repo again.
https://github.com/anton-karlovskiy/react-hooks-unit-test

I added some comments to help understanding.
I think this is not ideally perfect yet. I'm thinking of adding one more expect (the number of updateBatteryStatus called -> should be 3) for more confirm with the test result.

**Comment by housseindjirdeh** [comment]
Ah got it, you were still hooking up `monitorBattery` so that makes sense :) (and it already sets up the event listener)

It all looks good to me!! If you want to include an additional expect to check the number of times `updateBatteryStatus` is called then that will help for sure. 👍  

Right now `expect(result.current.updateBatteryStatus.length).toBe(1);` returns true so it isn't called more than once. But if you plan on updating it to it gets fired multiple times (due to level change for example) then that would be great!

**Comment by anton-karlovskiy** [comment]
Thank you @housseindjirdeh.

**Comment by addyosmani** [comment]
Overall, the error boundary implementations for the samples LGTM. I believe the fixes carried over from your repo based on @houssein's feedback should address the last round of feedback we had on the battery unit tests. Houssein, look good to you?

**Comment by housseindjirdeh** [comment]
Battery unit tests LGTM 👍

**Comment by addyosmani** [comment]
Thanks for the explanations, Anton. I'm happy to move forward with landing these changes. Appreciate all of the helpful input here too, @housseindjirdeh!

**Pull request merged**
